/**
 * Seed Data Verification Module.
 * Ensures seed user password hashes are bcryptjs-compatible at startup.
 *
 * Flow: SeedCheckFlow
 * Entrypoint: verifySeedPasswords()
 * Contract:
 *   - Checks all existing users whose password_hash uses $2b$ prefix
 *     (which may have been generated by a non-bcryptjs tool)
 *   - Attempts to verify the known seed password against stored hashes
 *   - Re-hashes with bcryptjs if verification fails
 *   - Only runs on known seed accounts (admin@enterprise.com, customer@example.com)
 * Errors: Logs warnings but does not throw (non-blocking)
 */
const bcrypt = require('bcryptjs');
const db = require('./pool');
const logger = require('../config/logger');

const SALT_ROUNDS = 12;

/**
 * Known seed accounts with their default passwords.
 * These are development-only defaults matching the database schema seed data.
 */
const SEED_ACCOUNTS = [
  { email: 'admin@enterprise.com', password: 'Admin123!' },
  { email: 'customer@example.com', password: 'Admin123!' },
];

// PUBLIC_INTERFACE
/**
 * Verify seed user password hashes are compatible with bcryptjs.
 * If a seed user's stored hash cannot verify against the known password,
 * re-hash it using bcryptjs. This handles the case where seed data was
 * inserted by a different bcrypt implementation (e.g., Python bcrypt uses $2b$).
 *
 * @returns {Promise<void>}
 */
async function verifySeedPasswords() {
  logger.info('SeedCheckFlow: verifying seed user password hashes');

  for (const account of SEED_ACCOUNTS) {
    try {
      const result = await db.query(
        'SELECT id, email, password_hash FROM users WHERE email = $1',
        [account.email]
      );

      if (result.rows.length === 0) {
        logger.debug('SeedCheckFlow: seed user not found, skipping', { email: account.email });
        continue;
      }

      const user = result.rows[0];
      const isValid = await bcrypt.compare(account.password, user.password_hash);

      if (isValid) {
        logger.debug('SeedCheckFlow: password hash OK', { email: account.email });
        continue;
      }

      // Re-hash with bcryptjs
      logger.warn('SeedCheckFlow: seed password hash incompatible, re-hashing', {
        email: account.email,
        hashPrefix: user.password_hash.substring(0, 7),
      });

      const newHash = await bcrypt.hash(account.password, SALT_ROUNDS);
      await db.query(
        'UPDATE users SET password_hash = $1 WHERE id = $2',
        [newHash, user.id]
      );

      logger.info('SeedCheckFlow: password hash updated for seed user', { email: account.email });
    } catch (error) {
      // Non-blocking: log and continue to next account
      logger.error('SeedCheckFlow: failed to verify seed user', {
        email: account.email,
        error: error.message,
      });
    }
  }

  logger.info('SeedCheckFlow: seed verification complete');
}

module.exports = { verifySeedPasswords };
